/* eslint-disable camelcase */
const kuromoji = require('kuromoji');
const { findIndex, flattenDeep, uniq } = require('lodash');
const fsSync = require('fs');
const fs = require('fs').promises;
const cliProgress = require('cli-progress');
const fetch = require('node-fetch');

// create a new progress bar instance and use shades_classic theme

// start the progress bar with a total value of 200 and start value of 0

// update the current value in your application..

// stop the progress bar

// eslint-disable-next-line no-underscore-dangle
let _pos = [];
let conjType = [];
let conjForm = [];

let basicForms = [];

const wordListFile = './wordList.json';

const pushInfNotExist = (array, value) => {
  const index = findIndex(array, ((v) => v.value === value));
  if (index === -1) return [...array, { value, occurences: 1 }];
  const updatedArray = [...array];

  updatedArray[index] = { ...updatedArray[index], occurences: updatedArray[index].occurences + 1 };
  return updatedArray;
};

const pushInfNotExistAndNotJp = (array, value) => {
  const newValue = value.replace(/[^ぁ-んァ-ン]|[^一-龯]/, '');
  if (!newValue) return array;

  return pushInfNotExist(array, newValue);
};

const wordListExists = fsSync.existsSync(wordListFile);

const parseBasicForms = ({ basic_form }) => {
  basicForms = pushInfNotExistAndNotJp(basicForms, basic_form);
};

const fetchAndWriteDefsInfos = async () => {
  const bar = new cliProgress.SingleBar({
    format: 'fetch [{bar}] {percentage}% | ETA: {eta}s | {value}/{total}',
  }, cliProgress.Presets.shades_classic);

  const bar2 = new cliProgress.SingleBar({
    format: 'parse [{bar}] {percentage}% | ETA: {eta}s | {value}/{total}',
  }, cliProgress.Presets.shades_classic);

  const bar3 = new cliProgress.SingleBar({
    format: 'info [{bar}] {percentage}% | ETA: {eta}s | {value}/{total}',
  }, cliProgress.Presets.shades_classic);

  const bar4 = new cliProgress.SingleBar({
    format: 'tags [{bar}] {percentage}% | ETA: {eta}s | {value}/{total}',
  }, cliProgress.Presets.shades_classic);

  try {
    const forms = (
      wordListExists
        ? await JSON.parse(fsSync.readFileSync(wordListFile))
        : basicForms.slice(1)
    );

    if (!wordListExists) fs.writeFile(wordListFile, JSON.stringify(forms));

    bar.start(forms.length, 0);

    const promises = forms.map(
      async ({ value: bf }, i) => {
        const fetcher = () => fetch(`http://localhost:3000/word/?${encodeURI(`word=${bf}`)}&handleAsWord=true`)
          .then(async (res) => {
            bar.increment();
            return res.json();
          });

        return (i % 250) ? fetcher() : setTimeout(fetcher, 500);
      },
    );

    // const promises = fetch(`http://localhost:3000/word/?${encodeURI(`word=${forms[0].value}`)}&handleAsWord=true`);

    const _tags = [];
    const _info = [];

    bar2.start(promises.length, 0);

    const data = await Promise.all(promises);

    data.forEach((({ words }) => {
      bar2.increment();
      if (!words) return;
      words.forEach(({ senses }) => senses.forEach(({ info, tags }) => {
        _tags.push(tags);
        _info.push(info);
      }));
    }));

    const filter = (_bar) => (arr) => uniq(flattenDeep(arr).filter((e) => {
      _bar.increment();
      return typeof e === 'string';
    }));

    const wf = async (_bar, path, arr) => (
      fs.writeFile(path, JSON.stringify(filter(_bar)(arr), null, 2)));

    bar3.start(_info.length, 0);
    await wf(bar3, 'info.json', _info);
    bar4.start(_tags.length, 0);
    await wf(bar4, 'tags.json', _tags);
  } catch (err) {
    bar.stop();
    bar2.stop();
    bar3.stop();
    bar4.stop();
    console.error('fetch failed', err);
  }
};

// eslint-disable-next-line no-unused-vars
const parseTokenDetailed = ({
  pos,
  pos_detail_1,
  pos_detail_2,
  pos_detail_3,
  conjugated_type,
  conjugated_form,
}) => {
  _pos = pushInfNotExist(_pos, pos);
  _pos = pushInfNotExist(_pos, pos_detail_1);
  _pos = pushInfNotExist(_pos, pos_detail_2);
  _pos = pushInfNotExist(_pos, pos_detail_3);
  conjType = pushInfNotExist(conjType, conjugated_type);
  conjForm = pushInfNotExist(conjForm, conjugated_form);
};

// eslint-disable-next-line no-unused-vars
const writeTokenDetailed = async () => {
  try {
    const sorter = (a, b) => b.occurences - a.occurences;
    const intermediate = (name) => ({ val: `======================${name}======================` });

    const allTokens = [
      intermediate('pos'),
      ..._pos.sort(sorter),
      intermediate('conjForm'),
      ...conjForm.sort(sorter),
      intermediate('conjType'),
      ...conjType.sort(sorter),
    ];

    await fs.writeFile('tokens.txt', JSON.stringify(allTokens, null, 2));
  } catch (err) {
    console.error(err);
  }
};

const readFile = (parseHandler, writeHandler) => {
  kuromoji.builder({ dicPath: 'node_modules/kuromoji/dict' }).build(async (err, tokenizer) => {
    if (err) return Promise.reject(err);

    try {
      console.log('reading file \n');
      const data = await fs.readFile('allhp', 'UTF-8');
      // split the contents by new line
      const lines = data.split(/\r?\n/);

      const bar = new cliProgress.SingleBar({
        format: 'tokenize [{bar}] {percentage}% | ETA: {eta}s | {value}/{total}',
      }, cliProgress.Presets.shades_classic);
      bar.start(lines.length, 0);

      lines.forEach((line, i) => {
        tokenizer
          .tokenize(line)
          .forEach(parseHandler);
        bar.update(i);
      });

      bar.stop();
      writeHandler();
    } catch (error) {
      Promise.reject(error);
    }
  });
};

// readFile(parseTokenDetailed, writeTokenDetailed)
// if (!wordListExists) {
//   readFile(parseBasicForms, fetchAndWriteDefsInfos);
// } else {
//   fetchAndWriteDefsInfos();
// }

const info = [
  'usu. after a verb',
  'also written 紀',
  '獲る esp. refers to catching wild game, etc.',
  'after the -masu stem of a verb',
  'usu. as お留守になる',
  'after the stem of an adjective',
  'indicates nationality, race, origin, etc.',
  'indicates expertise (in a certain field)',
  'usu. in compound words',
  'esp. ひのと',
  'esp. 丁番 in the construction industry',
  'orig. ichidan verb',
  'also 娘',
  'after a noun or -masu stem',
  "of one's equals",
  'orig. meaning',
  'before an adjective',
  'esp. 初, 初心',
  '産, 生',
  'esp. 戦う',
  'esp. 闘う',
  'used at sentence end',
  'れる for 五段 verbs, られる for 一段 verbs. After the -nai stem of a verb',
  'no imperative form, only on 一段',
  'no imperative form',
  'also as 繋ける',
  'after -masu stem of verb',
  'after -masu stem of verb; indicates an action is being directed to someone',
  'form: ...つ...つ',
  'after a noun that represents a state or condition; often as 〜裏に',
  'nuance of doing it easily',
  'also written as 犯土, 椎, 槌',
  'when speaking with a close friend',
  'usu. after the -masu stem of a verb as 〜出がある or 〜出がない, etc.',
  'indicates location of action; にて is the formal literary form',
  'indicates time of action',
  'indicates means of action',
  'indicates continuing action; alternative form of 〜て used for some verb types',
  'at sentence-end; indicates certainty, emphasis, etc.',
  'after a -nai stem',
  'as ＡもＢも',
  'used for emphasis or to express absence of doubt regarding a quantity, etc.',
  'often as 〜ても, 〜でも, 〜とも, etc.',
  'esp. 杜',
  '陌 and 佰 are used in legal documents',
  'usu. 元',
  'esp. 基',
  'also 因, 原',
  'esp. 素',
  'usu. 個',
  'sometimes derogatory',
  'usu. with volitional verb or adj. stem',
  'with neg. verb',
  'after an adverb',
  'sometimes esp. an emphatic form of the particle と',
  'often as ...とともに',
  'often as …はともかく',
  'also 硲',
  'after the dictionary form of a verb',
  'before a noun',
  'literary form of 為る',
  'after the imperfective form of certain verbs and adjectives',
  'as 〜することを得, etc.',
  '唄 is primarily used for shamisen songs',
  'on a 優, 良, 可 scale',
  'used at sentence-end; indicates a question (sometimes rhetorical)',
  'after each alternative',
  'after an interrogative',
  'indicates doubt, uncertainty, etc.; sometimes after other particles',
  'emphatic prefix; usu. before an adjective',
  'suffix forming adjectives or adverbs; after an indeclinable word',
  "used after a noun indicating someone's occupation, pursuits, disposition, etc.",
  'esp. え,べ',
  'possibly from 行李',
  'negative verb ending used in informal speech; abbr. of negative verb ending ぬ',
  'abbr. of particle の; indicates possessive',
  'abbr. of particle に, used esp. when it precedes the verb なる',
  'の and ん add emphasis',
  'from 〜のうち',
  'connects to ない stem',
  'at sentence end or as a noun suffix',
  'esp. 空ける',
  'esp. 明ける',
  '造る usu. for large-scale building, manufacturing, etc.; 創る usu. for creating',
  'usu. 官,司,寮',
  'usu. 首,長',
  'とわ tends to be more abstract',
  'がた when a suffix',
  'occasionally ん, orig. written 乃 or 之',
  'often ん',
  'indicates possessive; 之 used esp. on tombs',
  'after a number in the hito-, futa-, mi- counting system',
  '呑む often means swallowing whole, gulping, etc.',
  'also written 喫む',
  'usu. 割',
  'usu. 〜の割に(は)',
  'also written as 正',
  'used vocatively; esp. of an actor',
  'usu. 発つ',
  'var. of 崎 with 立 in the top right',
  '参 is used in legal documents',
  "after a person's name (or position, etc.)",
  'usu. after a noun or sometimes na-adjective',
  'after the name of a mountain',
  "after a temple's honorific mountain name",
  'in the form とおして…する',
  'after the -te form of a verb',
  'also pronounced どころ when a suffix',
  'after the plain past form of a verb',
  'after present form of a verb',
  'after past form of a verb',
  'しょたい is more informal',
  'imperative; after the -te form of a verb; pun on 見ろ',
  'ふ and ふう used mainly when counting aloud; 弐, 貳 and 貮 are used in legal documents.',
  'usu. 効く',
  'usu. 利く for body senses, functions, etc.',
  'usu. as お利口',
  'often as 〜が言う通りに〜 or 〜の言う通りに〜',
  'occ. pronounced た when a prefix',
  'casual quoting particle',
  'indicates supposition',
  'as かって; indicates a satirical or rhetorical question',
  'indicates certainty, insistence, emphasis, etc.',
  'abbr. of という',
  'abbr. of と言っている',
  'abbr. of と聞いている',
  'abbr. of とは, というのは',
  'equiv. of は topic marker',
  'で after certain verb forms',
  'used for non-exhaustive lists related to a specific time and place',
  'punctuational exclamation in haiku, renga, etc.',
  'interjection expressing surprise',
  'indicates a question',
  'usu. 屋',
  'usu. 屋, can be derog.',
  'usu. 家',
  '捌 is used in legal documents',
  'after numbers in the ichi, ni, san counting system',
  'used by police, crime reporters, etc.',
  'after an age',
  'after the -te form of a verb; irreg. imperative conj. of 見る',
  'as 〜てみると, 〜てみたら, 〜てみれば, etc.',
  'orig. an abbr. of 店棚;見世棚',
  '阡 and 仟 are used in legal documents',
  'ち only',
  'usu. ぢ',
  'usu. ったら',
  'expression of exasperation',
  'used after adj.',
  'after a noun or the stem of an adjective; usu. with a negative connotation',
  "used after a person's name, a personal pronoun, etc. in epistolary style",
  'usu. ぎゅう',
  'at sentence end',
  '拾 is used in legal documents',
  'after the -te form of a verb, indicates completion (and sometimes reluctance, accidentality, regret, etc.)',
  'as マウントを取る',
  'usu. 巻かれる',
  'usu. 巻(き)物',
  'usu. 巻きもの',
  'occ. written 度 (ateji)',
  'after the -ba stem of a verb',
  '玖 is used in legal documents',
  'usu. こう',
  'irreg. kanji form',
  'oft. after a noun+の or verb in the dictionary form',
  'oft. as フリ',
  "as …たり…たり, after the ren'youkei forms of multiple verbs",
  'used adverbially',
  "as …たり…たり at sentence-end, after the ren'youkei forms of a repeated verb",
  'from とあり, after a noun',
  "from 〜てあり, after the ren'youkei form of a verb",
  'in the form に足りる after a verb',
  'read as "ka"',
  'read as "ko"',
  'read as "ga"',
  'plain copula',
  'た after certain verb forms; indicates past or completed action',
  'indicates light imperative',
  'esp. 依る;拠る',
  'esp. 依る',
  'esp. 因る;由る',
  'esp. 拠る',
  'early Japanese Christian term',
  'esp. マス',
  'usu. in art contexts',
  'also written 種',
  'after a noun',
  'as 〜のもの, 〜のもん',
  'formal noun often used as 〜ものだ',
  'esp. 歌う, 詠う',
  'as AことB (A = alias, B = real name)',
  'as 〜ことはない',
  'as 〜ことだ',
  'often with a negative connotation',
  'higher than a 課',
  'following a unit of area (e.g. 町, 段, 畝)',
  'usu. as ～の声を聞く',
  'also read せい',
  'esp. 極める, 窮める',
  'esp. 究める',
  'ビール is sometimes written as 麦酒',
  'usu. ビーバー or ビーバ',
  'usu. ビバ or ビーバ',
  'as 〜をして in modern Japanese',
  "after the ren'youkei form of an adjective",
  'after an adverb or a particle',
  'later printed as 〓, resembling the teeth of a geta',
  'after -masu stem of verb; often ぐるしい',
  'also written 圕',
  'esp. 謀る',
  'またたく is sometimes used transitively',
  'esp. レーベル',
  'after the -nai stem of a verb',
  'usu. お〜',
  'い sometimes omitted in auxiliary use',
  'as ＡやらＢやら...',
  'usu. used in compound words',
  'after the -te form of a verb; indicates continuing action or state',
  "after -masu base of verb; indicates contempt or disdain for another's actions",
  'often as 〜然とする',
  'usu. with a negative verb',
  'oft. ビミョー',
  '肆 is used in legal documents',
  'usu. indicates one of several reasons',
  'at sentence end; gives reason for an unstated but deducible conclusion',
  'from ..て or で plus いる; indicates continuing action or state',
  'often as 無理に',
  'esp. 聴く',
  '聴く is used in legal and official contexts',
  'also 利く',
  'だあれ is emphatic or inquisitive',
  'of a plant',
  'usu. 履く or 穿く',
  'usu. 佩く or 帯く',
  'referring to someone of lower status',
  'sometimes pronounced ぴん',
  'esp. 品',
  'esp. 科',
  'sometimes pronounced ぼん, ぽん as a suffix',
  'mainly used in fixed expressions and compound verbs',
  'often 粕',
  'esp. 霞む',
  'esp. 翳む',
  'orig. used as an insult towards old-fashioned poets who would meet monthly to write poetry',
  'before a verb in negative form',
  'after a number or counter',
  'usu. as はい、チーズ',
  'esp. チラシ',
  'after a number',
  'also 徴',
  'counter for layers in the ichi-ni-san counting system',
  'usu. written as オモ',
  'counter for layers in the hito-futa-mi counting system',
  'police slang',
  'transliteration used in titles, etc.',
  'usu. 換え',
  'usu. 替える',
  'usu. 換える',
  'usu. 代える',
  'usu. in negative form',
  'after a currency',
  'after a number N',
  'follows verbs, adjectives',
  'following the te-form of a verb',
  'からだ is a gikun reading of 身体',
  'esp. 限り,限',
  'senses 6-8 are sometimes pronounced ぎり, esp. in old-fashioned speech',
  'usu. in a negative sentence',
  'also きり',
  'also written as 鑽る',
  'also written as 布, 裂',
  'esp. 受ける, 享ける',
  'esp. ウケる',
  'esp. 受ける, 承ける',
  'esp. 請ける, now primarily used in compound words',
  'esp. ウケる, うける',
  "from the bluish tinge of children's buttocks",
  'often as 〜空もない',
  'usu. as 空で',
  'before a noun or a verb',
  'み is generally used in compounds',
  'nominalizing suffix, esp. of sensory or subjective adjectives; also written with the ateji 味',
  'nominalizing suffix indicating location',
  'as ～み...～み',
  'semi-polite copula',
  'nominalizing suffix indicating degree or condition',
  'sentence end, mainly masc.',
  'e.g. 60の坂',
  'before a number of volumes',
  'with neg. sentence',
  'neg. context, e.g. 全然反対',
  'pos. context, e.g. 全然いいよ',
  'as 下から, 下より, etc.',
  'often のもとに or のもとで',
  'in the form ...のもとに',
  'usu. written 元',
  'after te-form of a verb or a noun prefixed with o- or go-',
  'esp. 下りる',
  'esp. 降りる',
  'in Kyoto',
  'esp. 降ろす',
  'often in neg. form',
  'also written as 瀉る',
  'esp. 尨毛',
  'esp. 毳',
  'esp. 球',
  'esp. 弾; also written as 弾丸',
  'esp. 玉,珠',
  'esp. 玉',
  'esp. 玉,珠; also written as 璧',
  'usu. だま',
  'also formerly read as ごく',
  '玉子 oft. used in cooking',
  'indicates emotional closeness or annoyance with someone',
  'indicates annoyance (in sentence-final position)',
  'used at end of sentence',
  'used mainly by women',
  'used to make casual requests or demands',
  '萬 is sometimes used in legal documents',
  'before a number',
  'lit. 1 in 10,000',
  'esp. 漬かる',
  'usu. セキ',
  'incorrect conjugation of いい',
  'used reproachfully',
  'as お+masu-stem+になる, ご+noun+になる, etc.',
  'from 鳴門海峡',
  'as 〜のほど',
  'oft. as 〜ば...ほど',
  'usu. as お運びになる, お運び下さる, etc.',
  'oft. as どう転んでも',
  'in early Japanese Christianity',
  'also written as 錬る',
  'also written as 邌る',
  'as 〜した日には, 〜と来た日には, etc.',
  'as 〜にする,〜とする',
  'as 〜にする',
  'as 〜がする',
  'as AをBにする',
  'as 〜うとする,〜ようとする',
  'sometimes written as 生命',
  'after the name of a god or a noble',
  'after noun, adjectival noun or adj. stem',
  'not ブルマーズ',
  'usu. in compounds',
  'originally written 麺麭 or 麪包',
  'esp. マシ',
  'usu. as 腹がいる',
  'usu. as ゆるがせに',
  'usu. 智慧',
  'used when counting by twos',
  'after past tense or past-continuous verb',
  '陸 is used in legal documents',
  'usu. in negative sentences',
  'usu. as 置き去りにする',
  'imperative',
  'imperative; after -te form of verb',
  'usu. verb-て...',
  'e.g. 田中チルドレン',
  'of things, not people',
  'often with で',
  '想う has connotations of heart-felt',
  'used in neg. form',
  'usu. in passive form',
  'esp. 返す',
  'criminal slang',
  'esp. 甚い',
  'usu. なう; esp. in status updates on social media',
  'after a noun or adj. stem',
  '1980s slang',
  'sometimes written as "Ｗ"',
  'alternative to ハーフ',
  'orig. an abbr. of ドルラル',
  'often read as づかい when used as a suffix',
  'often derog. or vulg.',
  'usu. 単',
  'as ...ことがない, etc.; indicates negation, inexperience, unnecessariness or impossibility',
  'verb-negating suffix; may indicate question or invitation with rising intonation',
  'after the root of an adjective',
  "usu. part of a 'nara' conditional",
  'often お急ぎ便',
  'esp. 険, but also written as 権 or 慳',
  'also 和',
  'slightly formal or feminine',
  'esp. 嗤い',
  'usu. 渡る or 渉る',
  'usu. 亘る or 亙る',
  'after a noun, etc.; when calling out to someone',
  'esp. しお',
  'esp. えん',
  'from 合点',
  'ateji derived from its call',
  'also written as 車厘',
  'esp. 折',
  'esp. 折り',
  'e.g. ★ or ☆',
  'esp. 塩梅',
  'esp. 按排, 按配, 案配, 安排',
  'pronounced ぐみ as a suffix',
  'esp. ノリ. possibly from 気乗り',
  'pronounced ずみ only when a suffix',
  'as 〜に暗い',
  'usu. ぐらし as a suffix',
  'orig. from 座居, meaning "seat"',
  'also written as 立',
  'from ブルマー and セーラー服',
  'esp. 濯ぐ',
  'esp. 雪ぐ',
  'as 〜の字',
  'used by children to their parents, etc.',
  'often 器械',
  'esp. 区切る',
  'esp. 句切る',
  'after a place name',
  'usu. as お平らに',
  'after a place name, usu. だいら',
  'abbr. of 単二型乾電池',
  '伍 is used in legal documents',
  'also ほう',
  'also がた',
  'as 〜のうち',
  'also 裡, 裏; as のうちに after a noun representing a state or condition',
  'also 家',
  "in a letter after the husband's name",
  'primarily used by women and children',
  'usu. as お下がり',
  'from 影ナレーション',
  'ピッカピカ and ビカビカ are more emphatic',
  'following -masu stem',
  'derogatory suffix (referring to others)',
  'humble suffix (referring to oneself)',
  'used to scold small children and pets',
  'also written as 洋袴 and 段袋 during the Meiji period',
  'ずーっと and ずうっと are more emphatic',
  'after an approximate quote or vague suggestion',
  'lessening the significance or value of the previous word',
  'poss. from 八九三',
  'usu. マリン',
  'esp. 外',
  'as 〜ほか〜ない, usu. after より or the dictionary form of a verb',
  'often as ほかに',
  'as 〜をよそに, 〜をよそにして, etc.',
  'from ..て and 上げる',
  'esp. 貼る',
  'sometimes じょうふ',
  'sometimes じょうぶ',
  'esp. 越える',
  'esp. 超える',
  'of soil',
  'ユイチー and イウチー are from Chinese "yuchi"',
  'indicates direction',
  "used to criticize someone's actions",
  'esp. 奔る',
  'esp. 趨る',
  'in Christianity and Judaism',
  'often with irony',
  'esp. 静まる',
  'esp. 鎮まる',
  'used for addressing young boys',
  'usu. as 見るからに',
  'usu. with an adverb of manner, e.g. よく乗る',
  'usu. 昇る',
  'usu. after dates',
  'usu. before names',
  'usu. 〜の亡者',
  'after the -ta form of a verb',
  'often オチ',
  'of animals',
  'of fish when it gets cold',
  'of an arrangement, conclusion, etc.',
  'usu. used pronominally as 落ち着いた',
  'used by the elderly',
  'suffix used in names',
  'also written as 起てる',
  'when urging or consoling',
  'when hesitating to express an opinion',
  'esp. 町',
  'expresses surprise, shock, doubt, etc.',
  '丸い usu. refers to ball-shaped, and 円い to disc-shaped objects',
  'also pronounced ぶくする',
  'esp. 嗤う',
  'as 笑ってしまう or 笑っちゃう',
  'expresses judgement based on evidence, reason or trustworthy hearsay',
  'after a noun, adverb or adj. stem',
  '臭い usu. has a negative connotation',
  'usu. 匂う',
  'usu. 臭う',
  '臭わす only used for unpleasant odours',
  'also written as 騰る in ref. to price',
  'often as 〜で上がる',
  'esp. 挙がる',
  '刻 signifies a time of day; 秋 signifies an important time',
  'after noun or -masu stem of verb',
  'pron. だより as a suffix',
  'often now as ...(を)求む',
  'orig. written as 牛皮',
  'usu. used prenominally',
  'esp. 撮る',
  'esp. 録る',
  'equiv. of -ている indicating continuing action as a verb ending',
  "セラピム from Latin 'seraphim'; セラヒン supposedly from Portuguese 'seraphin'",
  "used for others' actions",
  'used by Edo period prostitutes',
  'of film',
  'of a play, etc.',
  'after a noun; usu. read as だくさん',
  'also りち',
  'part of speech tag used in dictionaries',
  'esp. 止める, 停める',
  'esp. 留める',
  'used to scold or reprove',
  'used to call out to someone',
  'as 〜に強い',
  'usu. 勤める',
  'usu. 務める',
  'もううり is the Okinawan pronunciation',
  'at sentence end; indicates emphasis, agreement, request for confirmation, etc.',
  'esp. 値',
  'esp. 価',
  'usu. after a noun or na-adjective prefixed with お- or ご-',
  'esp. 速い, 疾い, 捷い',
  'esp. 早い',
  'usu. 早める',
  'usu. 速める',
  'esp. 速さ',
  'esp. 早さ',
  'かたぎ usu. as a suffix',
  'usu. as ご機嫌',
  'on (parking) entrance signs',
  'also written as 英蘭',
  "e.g. Ａ思いのＢ for 'B who loves A'",
  'づめ when a suffix',
  'usu. as 根を詰める',
  "the meaning \"to catch one's finger\" is predominantly used in Kansai",
  'often in the form …につまる',
  'esp. 印, 標',
  'also written as 徴',
  'esp. 証, 証し',
  'also written as 拍つ, 搏つ, 撲つ, 擣つ',
  'sometimes written as 株',
  'multiple repetitions of "w" ("LOL") resembles grass: wwwwww',
  'usu. as 心に記す, etc.',
  'also written as 炉裏',
  'after the Nabokov novel',
  'secret language of court ladies',
  'mostly arch. or in ref. to fruits, vegetables and traffic lights, etc.',
  'in ref. to facial colour',
  'from the play The Blue Bird by Maurice Maeterlinck',
  'used with neg. verb',
  'in the form に足る after a verb',
  'after a noun, usu. as 〜たる者, etc.; often used in relation to qualifications and requirements for a position',
  'usu. written as ナンパ',
  'pronounced ぎわ when a suffix',
  'of a person',
  'of a thing, incident, etc.',
  'used ironically; often as 可愛がってやる',
  'after a noun or the stem of an -i adjective',
  'yakuza slang',
  'ミクロトーム from German',
  'from たるい',
  'from Matthew 11:17',
  'on floor plans',
  'お医者さん is polite',
  'also written as 頒ける',
  "after someone's name or title",
  'used after a phone number',
  'used in dictionaries, etc.',
  'usu. as 〜代わりに, etc.',
  'usu. as お代わり',
  'esp. 替わり, 替り',
  'esp. 替わる, 替る',
  'esp. 代わる, 代る',
  'esp. 換わる, 換る',
  'じーっと is more emphatic. 凝乎と is rare.',
  'often as 冴えない',
  'original meaning; now somewhat old-fashioned',
  'also written as 呆んやり',
  'incorrect variant of やむを得ない',
  'in the negative',
  'after the volitional form of verb',
  'after the dictionary form of verb',
  'with を目的',
  'as 魚を開く',
  'as 体が開く, 肩が開く, etc.',
  'esp. 開く',
  'esp. 空く',
  'esp. 明く',
  'at sentence-end',
  'usu. as 2年縛り or 4年縛り',
  'esp. in Twitter',
  'esp. 患う',
  'esp. 煩う, after the -masu stem of a verb',
  'esp. 煩い',
  'esp. 患い',
  'as 決めている',
  'usu. as 決まりが悪い, etc.',
  'esp. ぬるぽ',
  'as 耳が遠い',
  'as 目が遠い',
  'poss. from Por: balanço',
  'slang, ksb, arch. equiv. of 早く',
  'ばえる, バエる are colloquial',
  'after a -masu stem',
  'also 虧ける',
  'often 私の方, あなたの方, etc.',
  'pluralizing suffix',
  'also かた',
  'after past tense verb',
  'after negative verb',
  'esp. 〜の香',
  'often written as アカ',
  '紅い is esp. for scarlet',
  'usu. before a term with an on-yomi reading',
  'after a noun indicating a person',
  'ご is gikun for 豆汁 and 豆油',
  'esp. 恃む',
  'in kyogen, etc.',
  'before a verb',
  'after a quantity',
  'after adjectival noun. e.g. 退屈極まる話',
  'esp. 窮まる. occ. 谷まる',
  'usu. リコーダー',
  'oft. as 〜ても仕方がない',
  'as 〜て仕方がない or 〜で仕方がない',
  'negative nuance, with the state being improper, unpleasant, etc.',
  'moan or groan (of pain)',
  'usu. used passively as 気取られる',
  'usu. ご都合がよろしい',
  'vocative',
  'orig. meaning, also written as 棚',
  'used to address a male patron, customer, or person of high status',
  'orig. meaning; usu. written as 檀那',
  'abbreviation of 栴檀林',
  'often as 湿って or 湿った',
  'old causative verbal ending',
  'also in 拳・けん',
  'from the number of fingers on both hands; used as secret jargon',
  'usu. 素声',
  'as きれいに',
  'esp. キッと',
  'sometimes written 緊い',
  'esp. 据わる, 据る',
  'epistolary style, sometimes also used as the name of the recipient',
  'before a place name',
  'usu. of inanimate objects',
  'usu. as 抜けた or 抜けている',
  'abbr. of いつものメンバー',
  'misspelling of 知れ渡る',
  'also used colloquially by young females',
  'usu. as 続けざまに',
  'in passive voice',
  'as 〜に手を触れる, 〜に口を触れる, etc.',
  'abbr. of "extract", not エキストラクト',
  'esp. エキストラ',
  'esp. エクストラ',
  'after the volitional form of a verb',
  'suffix used with the names of rivers',
  'Imperial Army jargon',
  'as 地味に',
  'as in 神',
  'after a noun or the -masu stem of a verb; also ったい',
  'after an article of clothing',
  'after a number in the ichi, ni counting system',
  'after a number in the hitotsu, futatsu counting system',
  'after a number of people',
  'after past tense of verb',
  'usu. 混じる',
  'usu. 交じる',
  'oft. ダレ in compounds',
  'used after a noun or na-adjective; also ったれ',
  'more emphatic than 誰も',
  'adv. equivalent of 誰でも; used with positive verbs',
  'abbr. of 誰が得する？',
  'as ぼそ',
  'いさら usu. refers to water',
  'billiards slang',
  'usu. 翔る. 翔ける, 一段 is unorthodox.',
  'usu. 駆ける',
  'sometimes written 掛ける',
  'in ball sports',
  'the city name is officially written in hiragana',
  'usu. as 珠玉の〜',
  'also written as 真珠',
  'of a guest, customer, etc.',
  'esp. 返る',
  'after the -masu stem of a verb; esp. 返る',
  'びくう is used by medical professionals',
  'usu. 挙げる',
  'after the -masu stem of a humble verb to increase the level of humility',
  'esp. 〜したあげく or 〜のあげく',
  'often ...も...ば...も...',
  'often ...ば...ほど',
  'ばけがく spoken to avoid confusion with 科学',
  'e.g. 40倍 - 1 in 40',
  "しい,しし, and しと were primarily children's words",
  'esp. 添う',
  'also written as 岐れる',
  'だ after certain verb forms; indicate past or completed action',
  'indicates mild imperative',
  'usu. as ～に',
  'literary form of 〜た',
  'esp. 木目',
  'esp. 杭, 杙',
  'esp. 株',
  'often as どうして、どうして',
  'with. neg. verb',
  'as いかに...も',
  'indicating emotive conviction',
  'indicating agreement',
  'also written 添う',
  'after -masu stem or adj. stem',
  "concerning the actions of the listener or concerning the ideas expressed or understood by the listener; with a neg. sentence, implies that something isn't as much as one might think",
  'used to express agreement with something said',
  'used to express doubt with something said',
  'usu. in titles of annotated editions of Confucian classics',
  'esp. 成す',
  'esp. 為す',
  'used for something or someone close to the speaker, including the speaker himself, or for the opinions of the speaker',
  'interjection used as a verbal pause',
  'in location names',
  'usu. コウ',
  'used in interrogative and hypothetical sentences',
  '米 is composed of 八十八',
  'usu. 覚書',
  'after plain verbs',
  'passive ending',
  'used to lament a particularly undesirable outcome or choice',
  'rarely used without a qualifier',
  'used as a conjunction or at sentence-end, often as 〜ものな, 〜ものね',
  'also いい (all senses)',
  'as て(も)良い, と(も)良い, etc.; indicates permission or compromise',
  'esp. 吉備団子',
  'esp. 黍団子',
  'esp. 利し, 鋭し',
  'esp. 疾し, 鋭し',
  'esp. 疾し, 捷し',
  'esp. 敏し, 聆し',
  'a variant of 喜 looks like 七十七 (77)',
  'used by elderly',
  'often abbr. 凸 on gay SNS sites',
  'from initials of Linux, Apache, MySQL, PHP',
  'also written as 間',
  'esp. 牽く',
  'not 抽斗,抽匣',
  "somewhat formal; not used for one's own family",
  'from C being the most difficult level in artistic gymnastics',
  'prohibitive; used with dictionary form verb',
  'imperative (from なさい); used with -masu stem of verb',
  'when seeking confirmation, for emphasis, etc.; used at sentence end',
  'used to express admiration, emotionality, etc.; used at sentence end',
  '漆 is used in legal documents',
  'usu. as お流れ',
  'followed by a counter',
  'followed by (optional number), counter and も',
  'expressing surprise',
  'expressing anger or irritability',
  'suffix often in kana',
  'usu. after a number',
  'as さすがの〜も',
  'esp. 納まる',
  '逢う is often used for close friends, etc. and may be associated with drama or pathos; 遭う may have an undesirable nuance',
  'esp. 遭う when in kanji',
  'from 尾行する and 付ける',
  'not used in the first person; たい with がる affixed',
  'usu. けい',
  'after a -masu stem, esp. of a suru verb',
  '掛 is often used for government offices, railways, etc.',
  'usu. as がりを食う',
  'usu. 昨夜',
  'as ...は...に限る',
  'after an adjective, verb, or noun',
  'after neg. verb',
  'usu. as 〜の限りではない',
  'esp. 閉まる',
  'not 閉め切り, etc.',
  'not 〆切, etc.',
  'usu. 締め切る',
  'esp. 〆',
  'variant of "cruz" from Portuguese',
  'on a sign',
  'often as 目をかすめて',
  'esp. 翳み,翳',
  'e.g. 門',
  'occ. written 杜父魚',
  'Buddhist priest jargon',
  'original meaning',
  'in place names',
  'sometimes read しま',
  'used in China',
  'usu. in the negative',
  'usu. adverbially as 代わり番こに',
  'usu. adverbially as 代わり番に',
  'esp. 足',
  'esp. 脚,肢',
  'usu. 脚',
  'usu. 粛として',
  'esp. 上 for stairs, 登 for mountain',
  "after the -te form or -masu stem of a verb; indicates hatred, contempt, or disdain for another's action",
  'as ～もくそも（ない）',
  "shouted in children's games or after accidentally touching something dirty",
  'usu. バリスタ',
  'usu. バリスター',
  'usu. のみくち',
  'usu. のみぐち',
  'in the form 幾+ctr+か',
  'in the form 幾+ctr+も',
  'はし refers to the stairs leading from a building to a garden',
  'mostly in compound words and in ref. to fruits, plants and traffic lights',
  'usu. as もやがかかって or もやがかかった',
  'also written as 保ち',
  'esp. 顎門, 顎, 腮',
  'esp. 鰓',
  "to one's inferior",
  'before an interrogative, forms an emphatic question',
  'emph. form of 一体',
  "'ranuki' equivalent of 見られる",
  'as をもちまして',
  'usu. as をもちまして',
  'often as 余計に',
  'from the image of Yukichi Fukuzawa on the front',
  'usu. plural',
  'esp. 掛かり, 掛り',
  'esp. 掛かり, 掛り; often as カカリ',
  'esp. for government offices, railways, etc.',
  'in the form もそこそこに',
  'in the ancient Chinese army',
  'euph. used during the first three days of the year',
  'sometimes 仁輪加 (ateji)',
  'esp. 合わせて, 合せて',
  'esp. 併せて',
  'esp. 慣れる',
  'esp. 馴れる',
  'usu. as ～の範囲内',
  'also うちどめる',
  '撃ち止める refers esp. to a gun, and 討ち止める to a blade',
  'esp. 固い and 堅い for wood, 硬い for metal and stone',
  'in the form に身をかためる',
  '鼠頭魚 is gikun',
  'usu. used in the negative',
  'used at sentence end; adds light force or emphasis to a sentence',
  'at sentence end; used to make a sentence threatening or ironic',
  'usu. in the negative as 承知しない',
  'often abbr. 凹 on gay SNS sites',
  'common error for 愛嬌を振りまく',
  'from 運がつく',
  'after -masu stems, onomatopoeic and mimetic words',
  'after noun+が, pronoun+の, etc.',
  'from someone of higher status',
  'used in mathematics to avoid writing out the original equation again in full',
  'from the initials of 空気（が）読めない',
  'from kanpai',
  'from the German "Konstruktions Punkt"',
  'abbr. of 結婚してください',
  'やや is an abbr. of ややこ',
  'usu. in the passive',
  'abbr. of 居残り勉強',
  'in the form of しわが寄る',
  'also written as 倚る, 凭る',
  'after the -masu stem of a verb; indicates contempt or disdain',
  'often むな as a prefix',
  'わからずや is a gikun reading of 没分暁漢',
  'sometimes びょう, ぴょう as a suffix',
  'from サボタージュ',
  'usu. さかい',
  'often ...を境に',
  'usu. きょう',
  'usu. with negative sentence',
  'contraction of ..て or で plus しまう',
  'after て form, slightly pompous',
  'usu. as べたに',
  'exclamation of surprise',
  '味 is ateji',
  'after an adj. stem or -masu stem of a verb',
  'from the Analects of Confucius',
  'from Mencius',
  'with verb in the negative',
  'used when bringing up something already mentioned',
  'literal meaning',
  'used toward people of equal or lower status',
  'わたくしりつ spoken to avoid confusion with 市立',
  '暖かい usu. refers to air temperature',
  'usu. after the -masu stem of a verb',
  'usu. after a noun',
  'on non-五段 stem, e.g. 食べる→食べよう; indicates intention',
  'on non-五段 stem; indicates suggestion or invitation',
  'on non-五段 stem; indicates speculation',
  'empathetic version of よ',
  'expressing incredulousness, sarcasm, disapproval, etc.',
  'usu. as 幼にして',
  'usu. as 〜も狭に',
  'oft. as 命の洗濯',
  'perhaps from "civil clothes" or "Savile Row"',
  'usu. as 〜に値する',
  'usu. 陥れる',
  'orig. meaning; usu. 落とし入れる',
  'former term',
  'orig. on an abacus',
  'when reading a number aloud; e.g. 20036 = 二万とびとび三十六',
  'from the sound of beating or striking',
  'used sarcastically',
  'usu. 凶',
  'usu. in suggestions or orders',
  'also written as 充て',
  'chanted repeatedly as a party cheer',
  'also 草',
  'used in place of だ when attributing an utterance to a Chinese person, poss. from Manchukuo dialect',
  'as あるいは...あるいは...',
  'used when calling out to somebody far away',
  'Tochigi dialect',
  'orig. 邌り, usu. お練り',
  'oft. as 人気がない/人気のない',
  'usu. not 間狭',
  'based on 回す',
  'often as 〜に渇いた',
  "epistolary style referring to a male who is one's equal or superior",
  'usu. as 変わった, 変わっている',
  'after negative base of verb',
  'usu. as 〜をいいことに(して)',
  'usu. as 〜を良いことに(して)',
  'used mainly in western Japan',
  'often 超す',
  'also read ベトナム',
  'usu. 〜の末',
  'as 〜の末 or 〜した末',
  'used after long, hard work',
  'with noun, e.g. 来週の末に',
  'contraction of わけがない',
  "expresses speaker's belief that something is impossible",
  'usu. as 異口同音に',
  'usu. 遅れる',
  'oft. 後れる',
  'often pronounced ずれ as a suffix',
  'usu. 治す',
  'usu. 直す',
  'after -masu base of verb; usu. 直す',
  'esp. 一人, １人',
  'esp. 独り',
  'also written as 羽子',
  'as 〜でも〜でも',
  'before an occupation, etc.',
  'である with も; formal, literary',
  'also んち or ち',
  'indicating that something is in the state of the preceding noun',
  'expression of physical exertion',
  'むな is usually used in compounds',
  'euphemistic',
  'as 〜するには当たらない, etc.',
  'usu. as 当たっている',
  'as 〜の〜に当たる',
  'after an adj. stem, onomatopoeic-mimetic word, etc.',
  'often 青々として',
  'usu. as イカれて（い）る',
  'esp. 野衾',
  'used by male children',
  'after name; familiar form of address',
  'often preceded by ん',
  'usu. 缶詰にする',
  'usu. 缶詰になる',
  'usu. as あたかものようだ, あたかものごとし, etc.',
  'esp. 精彩',
  'usu. 見事に',
  'also written as 宛',
  'also formerly written as 島 and 嶋',
  '殖える usu. refers to population growth or capital appreciation',
  'in Brazilian Japanese',
  'esp. 乗せる',
  'esp. 載せる',
  'also written as 襯衣',
  'esp. シミ',
  'also written 貫く',
  'as ...も何も',
  'as ...なくてもいい, ...ことはない, etc.',
  'usu. 祖母さん',
  '婆さん',
  'usu. 祖父さん',
  'usu. 爺さん',
  'on signage',
  'before a neg. form',
  'usu. as 〜にする',
  'esp. 丸',
  'usu. まるばしら',
  'likely from スーパー or スペシャル',
  'usu. as 身の置き所',
  'コアンチョウ and コワンチョウ are from Chinese',
  'often in neg.',
  'in western Japan, 買う conjugates euphonically as こうた, こうて, etc.',
  'used to silence someone',
  'used to drive off an approaching animal, etc.',
  'literary equiv. of だけ',
  'pun on 外人',
  'auxiliary used in place of ある after で or に when forming a copula',
  'auxiliary used in place of ます',
  'Often as ぞろい',
  'from the site of the crucial Battle of Yamazaki in 1582',
  'also written as 活',
  'as 〜に明るい',
  'esp. 慣らす',
  'esp. 馴らす',
  'usu. 習わす',
  'after the -masu stem of a verb; usu. 慣わす',
  'passive of 呼ぶ',
  'in the form 首を吊る',
  'esp. 鉉',
  'also written as 梁',
  'from ...か知らぬ, usu. fem',
  'indicates imprecision',
  'accompanied by a negative',
  'in self-reference; oft. as しこの',
  'usu. コミ',
  'esp. しい',
  'esp. しゆい',
  'from Guanzi',
  'after a noun, the -nai stem of a verb, or repetitive syllables',
  'usu. 腹を...',
  'e.g. 渕 as variant of 淵',
  'said to comfort a child in pain',
  'esp. あぶらぐすり',
  'usu. negative nuance',
  'esp. 冗員',
  'esp. 受付',
  'also written 岩',
  'esp. 飛ぶ',
  'esp. 跳ぶ',
  'non-standard var. of 鉢合わせする',
  'esp. 初め',
  'esp. 始め',
  'esp. 始め; as 〜を始め, 〜を始めとして, etc.',
  'as section heading of a book, etc.',
  'from John 1:1',
  'often used with command or request form addressing someone else',
  'as ～に憑く',
  'as もまれる',
  'from たまきえる',
  'the receiver is the speaker or someone close to the speaker',
  'often as くれてやる; shows mild disdain for the receiver',
  'used in ref. to places ending in 園',
  'esp. 伸ばす',
  'esp. 延ばす',
  'うるち refers only to rice',
  "of one's voice",
  '牛尾魚 is gikun',
  'often as 恐ろしく',
  'in careful usage 髭 for moustache, 鬚 for beard, 髯 for (cheek) whiskers',
  'esp. ヒモ',
  'esp. ヒケ',
  'esp. 注す',
  'esp. 点す',
  'スーッと and すうっと are more emphatic',
  'esp. 診てもらう',
  'usu. with neg. sentence',
  'also written 訓み',
  'paleography term',
  'as in 秘',
  'from Nonius (Nunes)',
  'oft. 札を崩す, etc.',
  'oft. as 字を崩す',
  'as 顔を崩す, etc.',
  'ばん when a suffix',
  'also written 板',
  'used with neg. verb, often as 微塵も〜ない',
  'ぬくい is primarily used in Western Japan',
  'from そそり立つ',
  'in ref. to objects, not to people',
  'used to strengthen expression of an emotion (often exasperation)',
  'esp. 〜した拍子に',
  'after modifying phrase',
  'often written as ハコ',
  'non-standard form of 込み上げる',
  'after a signature',
  'following a noun; used to mimic and mock people who are upset over something',
  "written on New Year's cards, etc.",
  '舟 is often small and hand-propelled',
  'ぼうぶら is primarily Kansai dialect',
  'named after the legend of Urashima Tarou',
  'epistolary style, used by men to address men',
  'usu. aux. verb',
  'esp. 憾み',
  "伯母 or 叔母 can mean older or younger than one's parent",
  "伯母さん is older than one's parent and 叔母さん is younger",
  '者 is ateji',
  'var. of 高 where the central top portion resembles a ladder',
  'emph. form of 若し, often in unfavorable situations',
  'because the Japanese hot spring symbol looks like an upside-down jellyfish',
  'esp. 名木',
  'esp. 疫病み',
  'esp. 瘧',
  'used with negative verb',
  'usually used in the negative sense',
  'before neg. verb',
  'in form Ａを欺くＢ',
  'esp. ぎへん',
  'sometimes used threateningly',
  'usu. with neg. verb',
  'irregular past tense conjugation of 綺麗',
  'oft. adv. as おうむ返しに',
  'at sentence end; short for ような気がする',
  'at sentence end; short for ような感じ（がする）',
  'しゃも from the old word for Siam',
  'oft. ぐさ in compounds',
  "after the -masu stem of a verb; indicates scorn or disdain for another's action",
  'used to state something assertively; orig. from じゃないか',
  'someone or something distant from both speaker and listener, or situation unfamiliar to both speaker and listener',
  'oft. as ...とか...とか',
  'used to convey hearsay or uncertain information; oft. with 言う, 聞く, etc.',
  'used to make a statement vague or less absolute; usu. after a noun',
  '熔かす and 鎔かす are used for metal',
  'often adds emphasis',
  'usu. after a family name',
  'often with negative verb',
  'after te-form of verbs and adj.',
  'more formal than 友達',
  'now a bit dated',
  'from 〜ずあり; used after a -nai stem',
  'from 〜ぞあり; usu. as 〜にざりける',
  'esp. かくけい',
  'at sentence-end; indicates certainty, emphasis, contempt, request, etc.',
  'after a noun; used when calling out to someone',
  "in mid-sentence; used to catch one's breath or get someone's attention",
  'now mostly used in idioms',
  'passive voice',
  'used when calling out to someone, somewhat aggressive',
  'also 著手',
  'とと and ちゃん are used by children',
  'before a number of years, e.g. 築十年',
  'after a time, e.g. 1980年築',
  'esp. スコンク',
  'usu. as 〜に',
  'usu. 撃つ',
  'usu. before a term with a kun-yomi reading; おん is more formal',
  'usu. お出でる or 御出でる',
  'after the 〜ず negative form of a verb; indicates disappointment',
  'esp. as レールを敷く',
  'before another loanword',
];

fs.writeFile('./info.json', JSON.stringify(info.sort(), null, 2));
